apiVersion: v1
kind: Pod
metadata:
  name: data-service
  labels:
    app: data-service-api
spec:
  containers:
    - name: web-data-service
      image: trevwhin/data-service:prod
      imagePullPolicy: Always
      ports:
        - containerPort: 4242
      envFrom:
        - configMapRef:
          name: data-service-config
      volumeMounts:
        - name: events-volume
          mountPath: /etc/config
  volumes:
    - name: events-volume
      configMap:
        name: events-config