apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4242
    nodePort: 31111
    protocol: TCP
  selector:
    app: data-service-api
    