apiVersion: v1
kind: Pod
metadata:
  name: data-service
  labels:
    app: data-service-api
spec:
  containers:
    - name: web-data-service
      image: trevwhin/data-service:1.3
      imagePullPolicy: Always
      ports:
        - containerPort: 4242
      envFrom:
        - configMapRef:
            name: data-service-config
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
    volumes:
      - name: config-volume
        configMap:
          name: data-service-config