apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongodb
spec:
  volumes:
    - name: hostmongo
      persistentVolumeClaim:
        claimName: mongo-pvc
  containers:
    - name: mongodb
      image: mongo
      imagePullPolicy: Always
      securityContext:
        privileged: true
      ports:
        - containerPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: hostmongo